SELECT * FROM customer_behavior.customer_shopping_behaviour;

-- 1.what is the total revenue generated bybmale vs. female?
SELECT gender, SUM(amount) as revenue
from customer_shopping_behaviour
group by gender;

-- 2.which customers used a discount but still spend more than the average amount?
SELECT id, amount
FROM customer_shopping_behaviour
WHERE discount_applied = 1 AND amount >= (SELECT AVG(amount) FROM customer_shopping_behaviour);

-- 3.which are the top5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS "Average Review Rating"
FROM customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
Limit 5;

-- 4.comapre the average purchase amount between standard and express shipping
SELECT shipping_type,
ROUND(AVG(amount), 2)
FROM customer_shopping_behaviour
WHERE shipping_type IN ("standard", "express")
GROUP BY shipping_type;

-- 5.do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers
SELECT subscription_status,
COUNT(id) AS Total_customers,
ROUND(AVG(amount), 2) AS Average_spend,
ROUND(SUM(amount), 2) AS Total_revenue
FROM customer_shopping_behaviour
GROUP BY subscription_status
ORDER BY Total_revenue, Average_spend DESC;

-- 6.which 5 products has the highest percentage of purchaes with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 1 THEN 1 else 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7.segment customers into new, returning and loyal based on their 
-- total number of previews purchases, and show the count of each segement
WITH customer_type AS (
	SELECT id, previous_purchases,
		CASE 
			WHEN previous_purchases = 1 THEN "new"
			WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
			ELSE "Loyal"
		END AS customer_segment
	FROM customer_shopping_behaviour
)
SELECT customer_segment, COUNT(*) AS "number_customers"
FROM customer_type
GROUP BY customer_segment;

-- 8. what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer_shopping_behaviour
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- 9.are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
SELECT subscription_status,
COUNT(id) AS repeat_buyer
FROM customer_shopping_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- 10.what is the revenue contribution of each age group?
SELECT age,
SUM(amount) AS total_revenue
FROM customer_shopping_behaviour
GROUP BY age
ORDER BY total_revenue DESC;



